# Generated by Django 5.0.6 on 2024-07-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_movie', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reies',
            new_name='Reviews',
        ),
    ]
