# Generated by Django 5.0.6 on 2024-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_movie', '0003_rename_reies_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(upload_to='media/actors/', verbose_name='Изображение'),
        ),
    ]
