# Generated by Django 5.0.6 on 2024-07-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_movie', '0004_alter_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='media/movie/', verbose_name='Постер'),
        ),
    ]
